name: mlflow_test
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - keras=2.4.3
  - tensorflow
  - numpy=1.19.1 
  - pandas=1.1.3
  - matplotlib=3.3.1
  - psycopg2=2.8.5
  - git=2.23.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - pip=20.3.3
  - pip:
    - mlflow==1.12.1
    - pysftp==0.2.9

